version: 2
jobs:
  shellcheck:
    docker:
      - image: nlknguyen/alpine-shellcheck:v0.4.6
    steps:
      - checkout
      - run:
          name: Check Scripts
          command: |
            find . -type f -name '*.sh' | wc -l
            find . -type f -name '*.sh' | xargs shellcheck --external-sources
  build-job:
    docker:
      - image: circleci/node:10 
    steps:
      - add_ssh_keys:
          fingerprints:
            - "e0:ba:8f:46:d3:a9:4a:fc:8e:c1:14:47:e8:ee:29:b7"
      - checkout
      - run:
          name: Deploy Wiki 
          command: ./scripts/deploy-wiki.sh

workflows:
  version: 2
  workflow:
    jobs:
      - shellcheck
      - build-job:
          requires:
            - shellcheck
          filters:
            branches:
              only: master